export enum PolicyStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  LAPSED = 'LAPSED',
  ARCHIVED = 'ARCHIVED',
}
