export enum PolicyTransitionAction {
  SUBMIT_FOR_APPROVAL = 'SUBMIT_FOR_APPROVAL',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  ACTIVATE = 'ACTIVATE',
  ISSUE = 'ISSUE',
  SUSPEND = 'SUSPEND',
  RESUME = 'RESUME',
  RENEW = 'RENEW',
  CANCEL = 'CANCEL',
  EXPIRE = 'EXPIRE',
  ARCHIVE = 'ARCHIVE',
}
